'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const {createHash}=require('node:crypto');
const {taskService,validateTask}=require('../server/task-service.cjs');const {oauthService}=require('../server/oauth.cjs');
// Isolated transactional store: queued transactions commit atomically; no Firebase or network access.
function memoryDB(initial={}) {
  const data=new Map(Object.entries(structuredClone(initial)));let tail=Promise.resolve();
  const snap=key=>({exists:data.has(key),data:()=>structuredClone(data.get(key))});
  const db={doc:key=>({key,get:async()=>snap(key),set:async value=>{data.set(key,structuredClone(value));},update:async value=>{if(!data.has(key))throw Error('missing');data.set(key,{...data.get(key),...structuredClone(value)});}}),runTransaction:fn=>{
    const work=tail.then(async()=>{const writes=[];const tx={get:async r=>snap(r.key),set:(r,v)=>writes.push(()=>data.set(r.key,structuredClone(v))),update:(r,v)=>writes.push(()=>data.set(r.key,{...data.get(r.key),...structuredClone(v)}))};const result=await fn(tx);writes.forEach(f=>f());return result;});tail=work.catch(()=>{});return work;
  }};return db;
}
const base=()=>({'workspace/proyectos':{standaloneTasks:[{id:'existing',text:'Existente',done:false}],projects:[{id:1,name:'Preservar'}],teamMembers:[{id:'GON',name:'Gon'}]}});
const input={requestId:'test_request_20260925',text:'Prueba chat',deadline:'2026-09-25'};
const actor={uid:'test-user'};
test('Disabled writes fail closed',async()=>{await assert.rejects(taskService(memoryDB(base())).create(input,actor),e=>e.code==='writes_disabled');});
test('Validate dates, text and unexpected fields',()=>{for(const change of [{deadline:'2026-02-30'},{text:'<img onerror=alert(1)>'},{extra:1},{requestId:'short'}])assert.throws(()=>validateTask({...input,...change}));});
test('Create persists correct deadline, actor and preserves unrelated data',async()=>{const db=memoryDB(base());const r=await taskService(db,{writesEnabled:true}).create(input,actor);assert.equal(r.presentNow,true);assert.equal(r.currentTask.deadline,'2026-09-25');const data=(await db.doc('workspace/proyectos').get()).data();assert.equal(data.standaloneTasks.length,2);assert.deepEqual(data.projects,[{id:1,name:'Preservar'}]);assert.equal(data.standaloneTasks[1].createdBy,actor.uid);});
test('Concurrent retries create exactly one task',async()=>{const db=memoryDB(base()),s=taskService(db,{writesEnabled:true});const results=await Promise.all([s.create(input,actor),s.create(input,actor)]);assert.equal((await db.doc('workspace/proyectos').get()).data().standaloneTasks.length,2);assert.equal(results.filter(r=>r.replayed).length,1);});
test('Concurrent distinct requests both persist',async()=>{const db=memoryDB(base()),s=taskService(db,{writesEnabled:true});await Promise.all([s.create(input,actor),s.create({...input,requestId:'other_request_20260925'},actor)]);assert.equal((await db.doc('workspace/proyectos').get()).data().standaloneTasks.length,3);});
test('Reuse with different payload rejected; deleted task never resurrected',async()=>{const db=memoryDB(base()),s=taskService(db,{writesEnabled:true});await s.create(input,actor);await assert.rejects(s.create({...input,text:'Otro'},actor),e=>e.code==='request_reused');await db.doc('workspace/proyectos').update({standaloneTasks:[]});const replay=await s.create(input,actor);assert.equal(replay.presentNow,false);assert.equal(replay.replayed,true);});
test('Unknown assignee rejected before write',async()=>{const db=memoryDB(base());await assert.rejects(taskService(db,{writesEnabled:true}).create({...input,responsibleId:'nobody'},actor),e=>e.code==='unknown_member');assert.equal((await db.doc('workspace/proyectos').get()).data().standaloneTasks.length,1);});
test('List has bounded scope and omits unrelated private fields',async()=>{const r=await taskService(memoryDB(base())).list({limit:1});assert.equal(r.scope,'standaloneTasks');assert.equal(r.tasks.length,1);assert.equal(r.projects,undefined);});
const cfg={origin:'https://bridge.example',resource:'https://bridge.example/mcp',clientId:'trazzo-chatgpt',redirects:['https://chatgpt.com/connector_platform_oauth_redirect'],allowedEmails:['allowed@example.com']};
function fixture(){let time=1000000;const db=memoryDB();const user={uid:'u',email:'allowed@example.com',emailVerified:true,disabled:false};const auth={getUser:async()=>user,verifyIdToken:async t=>{if(t!=='valid-id-token')throw Error('invalid');return {uid:'u',email:user.email,email_verified:user.emailVerified};}};return {oauth:oauthService(db,auth,cfg,{clock:()=>time}),user,tick:ms=>{time+=ms;}};}
const verifier='a'.repeat(43);const params={client_id:cfg.clientId,redirect_uri:cfg.redirects[0],resource:cfg.resource,response_type:'code',code_challenge_method:'S256',code_challenge:createHash('sha256').update(verifier).digest('base64url'),state:'user-state',scope:'tasks:read tasks:write'};
async function codeFor(f){const {session}=await f.oauth.begin(params);const redirect=new URL(await f.oauth.approve(session,'valid-id-token'));assert.equal(redirect.searchParams.get('state'),'user-state');assert.equal(redirect.searchParams.get('iss'),cfg.origin);return {session,body:{client_id:cfg.clientId,resource:cfg.resource,grant_type:'authorization_code',code:redirect.searchParams.get('code'),redirect_uri:params.redirect_uri,code_verifier:verifier}};}
test('OAuth rejects open redirects, wrong client, audience and PKCE downgrade',async()=>{const f=fixture();for(const p of [{redirect_uri:'https://evil.example'},{client_id:'evil'},{resource:'https://evil.example'},{code_challenge_method:'plain'}])await assert.rejects(f.oauth.begin({...params,...p}));});
test('OAuth consumes consent and code once; validates PKCE',async()=>{const f=fixture();const {session,body}=await codeFor(f);await assert.rejects(f.oauth.approve(session,'valid-id-token'));await assert.rejects(f.oauth.exchange({...body,code_verifier:'b'.repeat(43)}));const t=await f.oauth.exchange(body);assert.equal((await f.oauth.authenticate(t.access_token,'tasks:write')).uid,'u');await assert.rejects(f.oauth.exchange(body));});
test('Refresh rotates and revoke invalidates entire grant',async()=>{const f=fixture();const {body}=await codeFor(f);const first=await f.oauth.exchange(body);const b={client_id:cfg.clientId,resource:cfg.resource,grant_type:'refresh_token',refresh_token:first.refresh_token};const second=await f.oauth.exchange(b);await assert.rejects(f.oauth.exchange(b));await f.oauth.revoke(second.refresh_token,cfg.clientId);await assert.rejects(f.oauth.authenticate(first.access_token));await assert.rejects(f.oauth.authenticate(second.access_token));});
test('Expired token and removed/disabled users cannot access',async()=>{const f=fixture();const {body}=await codeFor(f);const t=await f.oauth.exchange(body);f.user.disabled=true;await assert.rejects(f.oauth.authenticate(t.access_token));f.user.disabled=false;f.tick(3600001);await assert.rejects(f.oauth.authenticate(t.access_token));});
test('Unverified and non-team identities cannot authorize',async()=>{for(const change of [{emailVerified:false},{email:'outsider@example.com'}]){const f=fixture();Object.assign(f.user,change);const {session}=await f.oauth.begin(params);await assert.rejects(f.oauth.approve(session,'valid-id-token'));}});
test('Read-only grant cannot create tasks',async()=>{const f=fixture();const {session}=await f.oauth.begin({...params,scope:'tasks:read'});const u=new URL(await f.oauth.approve(session,'valid-id-token'));const t=await f.oauth.exchange({client_id:cfg.clientId,resource:cfg.resource,grant_type:'authorization_code',code:u.searchParams.get('code'),redirect_uri:params.redirect_uri,code_verifier:verifier});await f.oauth.authenticate(t.access_token,'tasks:read');await assert.rejects(f.oauth.authenticate(t.access_token,'tasks:write'),e=>e.code==='insufficient_scope');});
test('MCP actual SDK advertises and calls tools over in-memory transport',async()=>{
 const {Client}=require('@modelcontextprotocol/sdk/client/index.js');const {InMemoryTransport}=require('@modelcontextprotocol/sdk/inMemory.js');const {createMcpServer}=require('../server/mcp.cjs');
 const db=memoryDB(base());const server=createMcpServer({authenticate:async()=>actor},taskService(db,{writesEnabled:true}),'test');const client=new Client({name:'test',version:'1'});const [a,b]=InMemoryTransport.createLinkedPair();await server.connect(a);await client.connect(b);
 try {const list=await client.listTools();assert.equal(list.tools.length,2);const result=await client.callTool({name:'crear_tarea',arguments:input});assert.equal(result.structuredContent.presentNow,true);const again=await client.callTool({name:'crear_tarea',arguments:input});assert.equal(again.structuredContent.replayed,true);}finally{await client.close();await server.close();}
});
test('HTTP handler without configuration returns 503, never opens access',async()=>{const handler=require('../api/trazzo.js');const old=process.env.TRAZZO_BRIDGE_ENABLED;delete process.env.TRAZZO_BRIDGE_ENABLED;const res={headers:{},setHeader(k,v){this.headers[k]=v;},end(s){this.body=JSON.parse(s);}};try{await handler({url:'/mcp',method:'POST',headers:{}},res);assert.equal(res.statusCode,503);assert.equal(res.body.error,'not_configured');}finally{if(old!==undefined)process.env.TRAZZO_BRIDGE_ENABLED=old;}});
